# Generated by Django 5.2.17 on 2026-08-16 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('citizens', '0002_refreshtoken'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneFreePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('daily_seconds', models.PositiveIntegerField(default=1800, help_text='Temps offert par période, en secondes.')),
                ('daily_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_session_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('cooldown_seconds', models.PositiveIntegerField(default=86400)),
                ('max_devices', models.PositiveSmallIntegerField(default=2)),
                ('usable_from', models.TimeField(blank=True, null=True)),
                ('usable_until', models.TimeField(blank=True, null=True)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_policy', to='network.zone')),
            ],
            options={
                'verbose_name': "politique d'accès gratuit",
                'verbose_name_plural': "politiques d'accès gratuit",
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('free', 'Attribution gratuite'), ('purchase', 'Achat'), ('voucher', 'Coupon'), ('sponsor', 'Sponsor')], max_length=20)),
                ('status', models.CharField(choices=[('pending_activation', "En attente d'activation"), ('active', 'Actif'), ('exhausted', 'Épuisé'), ('expired', 'Expiré'), ('suspended', 'Suspendu'), ('revoked', 'Révoqué'), ('activation_failed', "Échec d'activation")], default='pending_activation', max_length=25)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('radius_username', models.CharField(blank=True, max_length=120)),
                ('radius_synced_at', models.DateTimeField(blank=True, null=True)),
                ('activation_error', models.CharField(blank=True, max_length=200)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='citizens.citizen')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='catalog.planversion')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='network.zone')),
            ],
            options={
                'verbose_name': "droit d'accès",
                'verbose_name_plural': "droits d'accès",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['citizen', '-created_at'], name='access_enti_citizen_313767_idx'), models.Index(fields=['status'], name='access_enti_status_25f759_idx')],
            },
        ),
    ]
