# Generated by Django 5.2.17 on 2026-08-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_entitlement_order'),
        ('promotions', '0001_voucher_and_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='promotions.voucher'),
        ),
    ]
