# Generated by Django 5.2.17 on 2026-08-20 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_voucher_and_promotions'),
        ('citizens', '0002_refreshtoken'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radius_session_id', models.CharField(max_length=120, unique=True)),
                ('start_at', models.DateTimeField()),
                ('stop_at', models.DateTimeField(blank=True, null=True)),
                ('bytes_in', models.PositiveBigIntegerField(default=0)),
                ('bytes_out', models.PositiveBigIntegerField(default=0)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_sessions', to='citizens.citizen')),
                ('entitlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='network_session', to='access.entitlement')),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_sessions', to='network.hotspot')),
            ],
            options={
                'verbose_name': 'session réseau',
                'verbose_name_plural': 'sessions réseau',
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['citizen', '-start_at'], name='access_netw_citizen_281daa_idx')],
            },
        ),
    ]
