# Generated by Django 5.2.17 on 2026-08-16 17:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(choices=[('city', 'Ville'), ('district', 'Commune ou secteur'), ('partner', 'Partenaire')], default='city', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspendue'), ('archived', 'Archivée')], default='active', max_length=20)),
                ('openwisp_org_slug', models.SlugField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'organisation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('installing', 'En installation'), ('active', 'Actif'), ('degraded', 'Dégradé'), ('down', 'Hors service'), ('maintenance', 'Maintenance'), ('retired', 'Retiré')], default='planned', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text="Visible sur la carte publique des points d'accès.")),
                ('internet_provider', models.CharField(blank=True, max_length=100)),
                ('escalation_contact', models.CharField(blank=True, max_length=150)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='network.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('access_mode', models.CharField(choices=[('free', 'Gratuit'), ('paid', 'Payant'), ('sponsored', 'Sponsorisé'), ('hybrid', 'Hybride')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('suspended', 'Suspendue'), ('archived', 'Archivée')], default='draft', max_length=20)),
                ('timezone', models.CharField(default='Africa/Dakar', max_length=50)),
                ('welcome_message', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='network.site')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nas_identifier', models.CharField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('provider', models.CharField(blank=True, help_text='openwrt, unifi…', max_length=60)),
                ('external_id', models.CharField(blank=True, help_text='Identifiant du même équipement dans OpenWISP.', max_length=120)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('active', 'Actif'), ('degraded', 'Dégradé'), ('down', 'Hors service'), ('maintenance', 'Maintenance'), ('retired', 'Retiré')], default='planned', max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotspots', to='network.zone')),
            ],
            options={
                'ordering': ['nas_identifier'],
            },
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_site_name_per_organization'),
        ),
    ]
