# Generated by Django 5.2.17 on 2026-08-16 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('recipient_e164', models.CharField(max_length=20)),
                ('purpose', models.CharField(choices=[('otp', 'Code de vérification'), ('notification', 'Notification')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('sent', 'Envoyé'), ('delivered', 'Remis'), ('failed', 'Échec')], default='queued', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('cost_xof', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='messaging_s_provide_a646c5_idx')],
            },
        ),
    ]
