# Generated by Django 5.2.17 on 2026-08-16 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('citizens', '0002_refreshtoken'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(editable=False, max_length=24, unique=True)),
                ('amount_xof', models.PositiveIntegerField()),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de paiement'), ('requires_action', 'Action requise'), ('paid', 'Payée'), ('failed', 'Échouée'), ('expired', 'Expirée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée'), ('partially_refunded', 'Partiellement remboursée')], default='draft', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('reactivated_after_expiry', models.BooleanField(default=False)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='citizens.citizen')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.planversion')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='network.zone')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('mode', models.CharField(choices=[('push', 'Push mobile'), ('redirect', 'Redirection')], max_length=10)),
                ('external_reference', models.CharField(db_index=True, max_length=120)),
                ('amount_xof', models.PositiveIntegerField()),
                ('fees_xof', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('succeeded', 'Réussi'), ('refused', 'Refusé'), ('expired', 'Expiré')], default='initiated', max_length=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.order')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('external_event_id', models.CharField(max_length=120)),
                ('signature_valid', models.BooleanField(default=False)),
                ('outcome', models.CharField(choices=[('processed', 'Traité'), ('duplicate', 'Doublon'), ('bad_signature', 'Signature invalide'), ('amount_mismatch', 'Montant divergent'), ('unknown_order', 'Commande inconnue'), ('ignored', 'Ignoré')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('body_sha256', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='billing.order')),
            ],
            options={
                'verbose_name': 'événement de webhook',
                'verbose_name_plural': 'événements de webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expires_at'], name='billing_ord_status_49b5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['citizen', '-created_at'], name='billing_ord_citizen_63a7b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('citizen', 'idempotency_key'), name='one_order_per_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'external_event_id'], name='billing_web_provide_0be915_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('outcome', 'processed')), fields=('provider', 'external_event_id'), name='one_processed_delivery_per_event'),
        ),
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS billing_order_number_seq START 1;",
            reverse_sql="DROP SEQUENCE IF EXISTS billing_order_number_seq;",
        ),
    ]
