# Generated by Django 5.2.17 on 2026-08-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='redirect_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
