# Generated by Django 5.2.17 on 2026-08-20 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_redirect_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('running', 'En cours'), ('balanced', 'Équilibré'), ('mismatch', 'Écart'), ('failed', 'Échoué')], default='running', max_length=12)),
                ('totals_json', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'rapprochement',
                'verbose_name_plural': 'rapprochements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_xof', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('requested', 'Demandé'), ('succeeded', 'Réussi'), ('failed', 'Échoué')], default='requested', max_length=12)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.payment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'remboursement',
                'verbose_name_plural': 'remboursements',
                'ordering': ['-created_at'],
            },
        ),
    ]
