# Generated by Django 5.2.17 on 2026-08-16 19:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Traité'), ('failed', 'Échec définitif')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': "message d'outbox",
                'verbose_name_plural': "messages d'outbox",
                'ordering': ['available_at'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='core_outbox_status_79e487_idx')],
            },
        ),
    ]
