# Generated by Django 5.2.17 on 2026-08-16 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('free', 'Gratuit'), ('paid', 'Payant'), ('sponsored', 'Sponsorisé'), ('hybrid', 'Hybride')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('suspended', 'Suspendu'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('sale_starts_at', models.DateTimeField(blank=True, null=True)),
                ('sale_ends_at', models.DateTimeField(blank=True, null=True)),
                ('usable_from', models.TimeField(blank=True, null=True)),
                ('usable_until', models.TimeField(blank=True, null=True)),
                ('renewal_policy', models.TextField(blank=True)),
                ('refund_policy', models.TextField(blank=True)),
                ('zones', models.ManyToManyField(blank=True, related_name='plans', to='network.zone')),
            ],
            options={
                'verbose_name': 'offre',
                'verbose_name_plural': 'offres',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('price_xof', models.PositiveIntegerField(default=0)),
                ('connection_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('validity_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('quota_total_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('quota_download_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('quota_upload_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('bandwidth_down_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('bandwidth_up_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('max_simultaneous_sessions', models.PositiveSmallIntegerField(default=1)),
                ('radius_profile_ref', models.CharField(blank=True, max_length=120)),
                ('effective_at', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalog.plan')),
            ],
            options={
                'verbose_name': "version d'offre",
                'verbose_name_plural': "versions d'offre",
                'ordering': ['plan', '-version'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.planversion'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version'), name='unique_version_per_plan'),
        ),
    ]
