# Generated by Django 5.2.17 on 2026-08-20 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_entitlement_order'),
        ('catalog', '0001_initial'),
        ('citizens', '0002_refreshtoken'),
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='draft', max_length=20)),
                ('contact_data', models.JSONField(blank=True, default=dict)),
                ('partner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sponsor',
                'verbose_name_plural': 'sponsors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('ended', 'Terminée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('budget_xof', models.PositiveIntegerField(blank=True, null=True)),
                ('zones', models.ManyToManyField(blank=True, related_name='campaigns', to='network.zone')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='promotions.sponsor')),
            ],
            options={
                'verbose_name': 'campagne',
                'verbose_name_plural': 'campagnes',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('codes_exported_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='promotions.campaign')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_batches', to='catalog.planversion')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_batches', to='network.zone')),
            ],
            options={
                'verbose_name': 'lot de coupons',
                'verbose_name_plural': 'lots de coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(db_index=True, max_length=4)),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('unused', 'Non utilisé'), ('active', 'Actif'), ('exhausted', 'Épuisé'), ('expired', 'Expiré'), ('revoked', 'Révoqué')], default='unused', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='promotions.voucherbatch')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['prefix'],
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_redemptions', to='citizens.citizen')),
                ('entitlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_redemption', to='access.entitlement')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.voucher')),
            ],
            options={
                'verbose_name': 'consommation de coupon',
                'verbose_name_plural': 'consommations de coupons',
                'constraints': [models.UniqueConstraint(fields=('citizen', 'idempotency_key'), name='one_voucher_redemption_per_idempotency_key'), models.UniqueConstraint(fields=('citizen', 'voucher'), name='one_redemption_per_citizen_per_voucher')],
            },
        ),
    ]
