# Generated by Django 5.2.17 on 2026-08-20 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_number', models.CharField(editable=False, max_length=24, unique=True)),
                ('priority', models.CharField(choices=[('p1', 'P1 — critique'), ('p2', 'P2 — majeur'), ('p3', 'P3 — mineur'), ('p4', 'P4 — faible')], default='p3', max_length=4)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('acknowledged', 'Pris en charge'), ('waiting', 'En attente'), ('resolved', 'Résolu'), ('closed', 'Clos')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('automatic', 'Automatique')], default='manual', max_length=20)),
                ('alert_type', models.CharField(choices=[('equipment_offline', 'Équipement hors ligne'), ('degraded', 'Dégradé'), ('other', 'Autre')], default='other', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='network.hotspot')),
            ],
            options={
                'verbose_name': 'incident',
                'verbose_name_plural': 'incidents',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['status', '-opened_at'], name='incidents_i_status_73e437_idx'), models.Index(fields=['incident_number'], name='incidents_i_inciden_40c621_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'acknowledged', 'waiting'])), fields=('hotspot', 'alert_type'), name='one_open_incident_per_hotspot_alert')],
            },
        ),
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS incidents_incident_number_seq START 1;",
            reverse_sql="DROP SEQUENCE IF EXISTS incidents_incident_number_seq;",
        ),
    ]
