# Generated by Django 5.2.17 on 2026-08-16 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof'), ('en', 'English')], default='fr', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'En attente de vérification'), ('active', 'Actif'), ('blocked', 'Bloqué'), ('deleted', 'Supprimé')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('radius_username', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'citoyen',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='citizens_ci_status_aa4383_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('device_hint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('verified', 'Vérifié'), ('expired', 'Expiré'), ('failed', 'Échec de vérification')], default='sent', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'demande OTP',
                'verbose_name_plural': 'demandes OTP',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['phone_e164', '-sent_at'], name='citizens_ot_phone_e_4997b3_idx'), models.Index(fields=['ip_hash', '-sent_at'], name='citizens_ot_ip_hash_b6895f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('terms', "Conditions d'utilisation"), ('privacy', 'Politique de confidentialité')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('content_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'version des conditions',
                'verbose_name_plural': 'versions des conditions',
                'ordering': ['type', '-published_at'],
                'constraints': [models.UniqueConstraint(fields=('type', 'version'), name='unique_terms_version')],
            },
        ),
        migrations.CreateModel(
            name='CitizenDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mac_hash', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('trusted_until', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='citizens.citizen')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('citizen', 'mac_hash'), name='unique_device_per_citizen')],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField()),
                ('source', models.CharField(default='portal', max_length=40)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='citizens.citizen')),
                ('terms_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='citizens.termsversion')),
            ],
            options={
                'verbose_name': 'consentement',
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('citizen', 'terms_version'), name='unique_consent_per_version')],
            },
        ),
    ]
