# Generated by Django 5.2.17 on 2026-08-16 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='citizens.citizen')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='citizens.refreshtoken')),
            ],
            options={
                'verbose_name': 'jeton de rafraîchissement',
                'verbose_name_plural': 'jetons de rafraîchissement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['citizen', '-created_at'], name='citizens_re_citizen_4a0db6_idx')],
            },
        ),
    ]
