# Generated by Django 5.2.17 on 2026-08-20 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0004_network_session_and_support_ticket'),
        ('billing', '0003_refund_and_reconciliation'),
        ('citizens', '0002_refreshtoken'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(editable=False, max_length=24, unique=True)),
                ('category', models.CharField(choices=[('connexion', 'Connexion'), ('otp', 'Code SMS'), ('paiement', 'Paiement'), ('quota', 'Quota'), ('qualite', 'Qualité'), ('autre', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('waiting', 'En attente'), ('resolved', 'Résolu'), ('closed', 'Clos')], default='open', max_length=20)),
                ('message', models.TextField()),
                ('diagnostic_notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='citizens.citizen')),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='network.hotspot')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='billing.order')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='access.networksession')),
            ],
            options={
                'verbose_name': 'ticket de support',
                'verbose_name_plural': 'tickets de support',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['status', '-opened_at'], name='support_sup_status_e38226_idx'), models.Index(fields=['ticket_number'], name='support_sup_ticket__4a7d4b_idx')],
            },
        ),
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS support_ticket_number_seq START 1;",
            reverse_sql="DROP SEQUENCE IF EXISTS support_ticket_number_seq;",
        ),
    ]
