/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fermer la session */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demander un code de vérification */
        post: operations["auth_otp_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vérifier le code et ouvrir une session */
        post: operations["auth_otp_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renouveler la session */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * État de santé du service
         * @description Liveness and readiness probe.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil du citoyen connecté */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Droits d'accès du citoyen connecté */
        get: operations["me_entitlements_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commander une offre payante */
        post: operations["orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statut d'une commande */
        get: operations["orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reçu d'une commande payée */
        get: operations["orders_receipt_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portal/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contexte du portail pour une borne */
        get: operations["portal_context_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portal/free-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activer l'accès gratuit de la zone */
        post: operations["portal_free_access_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portal/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offres disponibles pour une borne */
        get: operations["portal_plans_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portal/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conditions à accepter */
        get: operations["portal_terms_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/hotspots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Carte publique des points d'accès
         * @description Sites the City publishes on its public map.
         *
         *     Only sites explicitly marked public and actually geolocated are returned, and
         *     no equipment identifier ever leaves this endpoint (§8.9).
         */
        get: operations["public_hotspots_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/payments/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook de paiement */
        post: operations["webhooks_payments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Citizen: {
            /** Format: uuid */
            id: string;
            phone_e164: string;
            email: string;
            preferred_language: string;
            status: string;
            /** Format: date-time */
            verified_at: string | null;
        };
        Entitlement: {
            /** Format: uuid */
            id: string;
            source: string;
            status: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string | null;
            readonly zone: string;
            readonly plan: string;
        };
        EntitlementList: {
            entitlements: components["schemas"]["Entitlement"][];
        };
        Error: {
            code: string;
            message: string;
            request_id: string;
        };
        Fallback: {
            active: boolean;
            reason: string;
        };
        FreeAccessRequestRequest: {
            nas_id: string;
        };
        Health: {
            /** @description 'ok' or 'unavailable' */
            status: string;
            /** @description local, test, staging or production */
            environment: string;
            version: string;
            checks: components["schemas"]["HealthChecks"];
        };
        HealthChecks: {
            /** @description 'ok' or 'error' */
            database: string;
            /** @description 'ok' or 'error' */
            cache: string;
        };
        Order: {
            /** Format: uuid */
            readonly id: string;
            readonly order_number: string;
            amount_xof: number;
            currency?: string;
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            paid_at?: string | null;
            /** @default  */
            readonly mode: string;
            /** @default  */
            readonly instructions: string;
            readonly redirect_url: string;
            readonly entitlement_status: string;
        };
        OrderRequestRequest: {
            nas_id: string;
            /** Format: uuid */
            plan_version_id: string;
        };
        OtpRequestRequest: {
            phone: string;
        };
        OtpVerifyRequest: {
            phone: string;
            code: string;
            accepted_terms: string[];
        };
        /**
         * @description Public view of an offer.
         *
         *     Deliberately omits `radius_profile_ref`: RADIUS references belong to the network
         *     layer and must never appear in a payload served to a browser (§8.9).
         */
        PlanOffer: {
            code: string;
            name: string;
            description: string;
            type: string;
            readonly price_xof: number;
            readonly currency: string;
            readonly connection_seconds: number | null;
            readonly validity_seconds: number | null;
            readonly quota_total_bytes: number | null;
            readonly bandwidth_down_kbps: number | null;
            readonly bandwidth_up_kbps: number | null;
            readonly max_simultaneous_sessions: number;
        };
        PortalContext: {
            zone: components["schemas"]["Zone"];
            site: components["schemas"]["Site"];
            fallback: components["schemas"]["Fallback"];
            plans: components["schemas"]["PlanOffer"][];
            redirect_url: string | null;
        };
        PortalPlans: {
            plans: components["schemas"]["PlanOffer"][];
        };
        /** @description Map entry. Carries nothing that identifies equipment (§8.9). */
        PublicSite: {
            name: string;
            address: string;
            /** Format: decimal */
            latitude: string;
            /** Format: decimal */
            longitude: string;
            status: string;
            hotspot_count: number;
            access_modes: string[];
        };
        PublicSites: {
            sites: components["schemas"]["PublicSite"][];
        };
        Receipt: {
            readonly order_number: string;
            readonly plan_name: string;
            amount_xof: number;
            currency?: string;
            /** Format: date-time */
            paid_at?: string | null;
        };
        RefreshRequest: {
            refresh: string;
        };
        Site: {
            name: string;
            address: string;
            readonly organization: string;
        };
        /**
         * @description * `draft` - Brouillon
         *     * `pending` - En attente de paiement
         *     * `requires_action` - Action requise
         *     * `paid` - Payée
         *     * `failed` - Échouée
         *     * `expired` - Expirée
         *     * `cancelled` - Annulée
         *     * `refunded` - Remboursée
         *     * `partially_refunded` - Partiellement remboursée
         * @enum {string}
         */
        StatusEnum: "draft" | "pending" | "requires_action" | "paid" | "failed" | "expired" | "cancelled" | "refunded" | "partially_refunded";
        TermsList: {
            terms: components["schemas"]["TermsVersion"][];
        };
        TermsVersion: {
            /** Format: uuid */
            id: string;
            type: string;
            version: string;
            content_url: string;
            summary: string;
        };
        TokenPair: {
            access: string;
            refresh: string;
            access_expires_in: number;
            citizen: components["schemas"]["Citizen"];
        };
        Zone: {
            code: string;
            label: string;
            access_mode: string;
            timezone: string;
            welcome_message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RefreshRequest"];
                "multipart/form-data": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_otp_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpRequestRequest"];
                "multipart/form-data": components["schemas"]["OtpRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_otp_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpVerifyRequest"];
                "multipart/form-data": components["schemas"]["OtpVerifyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RefreshRequest"];
                "multipart/form-data": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Citizen"];
                };
            };
        };
    };
    me_entitlements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementList"];
                };
            };
        };
    };
    orders_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OrderRequestRequest"];
                "multipart/form-data": components["schemas"]["OrderRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    orders_receipt_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    portal_context_retrieve: {
        parameters: {
            query: {
                /** @description Identifiant réseau présenté par la borne. Seule source de vérité pour résoudre la zone. */
                nas_id: string;
                /** @description URL de retour fournie par la passerelle. Ignorée si son hôte n'est pas explicitement autorisé. */
                redirect_url?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalContext"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    portal_free_access_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FreeAccessRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FreeAccessRequestRequest"];
                "multipart/form-data": components["schemas"]["FreeAccessRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entitlement"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    portal_plans_retrieve: {
        parameters: {
            query: {
                /** @description Identifiant réseau présenté par la borne. Seule source de vérité pour résoudre la zone. */
                nas_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalPlans"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    portal_terms_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermsList"];
                };
            };
        };
    };
    public_hotspots_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSites"];
                };
            };
        };
    };
    webhooks_payments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
